spring.application.name=Brasileiras
spring.datasource.url=jdbc:mysql://localhost:3306/brasileirasdb
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false